<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Authors>zacala1</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" />
    <PackageReference Include="ClosedXML" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CuttingStock.Core\CuttingStock.Core.csproj" />
  </ItemGroup>

</Project>
